# Generated by Django 4.1.7 on 2023-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='pics')),
                ('Name', models.CharField(max_length=250)),
                ('Description', models.TextField()),
            ],
        ),
    ]
