# Generated by Django 4.1.7 on 2023-03-06 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Demo',
            new_name='Place',
        ),
    ]
